name: Publish - Active Directory Module
on: [workflow_dispatch]

jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - name: Release
          run: .\Components\ActiveDirectory\release.ps1
          env:
            PowerShellGalleryKey: ${{ secrets.POWERSHELL_GALLERY_KEY }}
          shell: pwsh